version: '3'

services:

  konga:
    image: konga
    ports:
      - 1337:1337
    container_name: konga
    environment:
      - NODE_ENV=production
      - KONGA_AUTH_PROVIDER=ldap
      - KONGA_LDAP_HOST=ldaps://ORG.ldap.okta.com:636
      - KONGA_LDAP_USER_SEARCH_BASE=ou=users,dc=ORG,dc=okta,dc=com
      - KONGA_LDAP_GROUP_SEARCH_BASE=ou=groups,dc=ORG,dc=okta,dc=com
      - KONGA_ADMIN_GROUP_REG=^(konga_admins)$$
      - KONGA_LDAP_BIND_DN=uid=user@domain.com,dc=ORG,dc=okta,dc=com
      - KONGA_LDAP_BIND_PASSWORD=pass
      - KONGA_LDAP_USER_SEARCH_FILTER=(uid={{username}})
      - KONGA_LDAP_USER_ATTRS=uid,givenName,sn	
      - KONGA_LDAP_GROUP_SEARCH_FILTER=(uniqueMember={{dn}})
      - KONGA_LDAP_ATTR_EMAIL=uid
      - KONGA_KONGS_ARRAYS={"Konga":"https://staging-kong.domain.com","Konga2":"https://productin-kong.domain.com"} 

networks:
  kong-net:
    external: false